In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv('Test.csv')

In [3]:
ds

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDW58       20.750          Low Fat         0.007565   
1              FDW14        8.300              reg         0.038428   
2              NCN55       14.600          Low Fat         0.099575   
3              FDQ58        7.315          Low Fat         0.015388   
4              FDY38          NaN          Regular         0.118599   
...              ...          ...              ...              ...   
5676           FDB58       10.500          Regular         0.013496   
5677           FDD47        7.600          Regular         0.142991   
5678           NCO17       10.000          Low Fat         0.073529   
5679           FDJ26       15.300          Regular         0.000000   
5680           FDU37        9.500          Regular         0.104720   

               Item_Type  Item_MRP Outlet_Identifier  \
0            Snack Foods  107.8622            OUT049   
1                  Dairy   87.3198            OUT017   
2                 Others  241.7538            OUT010   
3            Snack Foods  155.0340            OUT017   
4                  Dairy  234.2300            OUT027   
...                  ...       ...               ...   
5676         Snack Foods  141.3154            OUT046   
5677       Starchy Foods  169.1448            OUT018   
5678  Health and Hygiene  118.7440            OUT045   
5679              Canned  214.6218            OUT017   
5680              Canned   79.7960            OUT045   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2007         NaN               Tier 2   
2                          1998         NaN               Tier 3   
3                          2007         NaN               Tier 2   
4                          1985      Medium               Tier 3   
...                         ...         ...                  ...   
5676                       1997       Small               Tier 1   
5677                       2009      Medium               Tier 3   
5678                       2002         NaN               Tier 2   
5679                       2007         NaN               Tier 2   
5680                       2002         NaN               Tier 2   

            Outlet_Type  
0     Supermarket Type1  
1     Supermarket Type1  
2         Grocery Store  
3     Supermarket Type1  
4     Supermarket Type3  
...                 ...  
5676  Supermarket Type1  
5677  Supermarket Type2  
5678  Supermarket Type1  
5679  Supermarket Type1  
5680  Supermarket Type1  

[5681 rows x 11 columns]

In [4]:
ds.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],
      dtype='object')

In [5]:
A=ds[['Item_Identifier', 'Item_Weight']].values


In [6]:
A

array([['FDW58', 20.75],
       ['FDW14', 8.3],
       ['NCN55', 14.6],
       ...,
       ['NCO17', 10.0],
       ['FDJ26', 15.3],
       ['FDU37', 9.5]], dtype=object)

In [7]:
B=ds[['Item_Fat_Content', 'Item_Visibility']].values

In [8]:
B

array([['Low Fat', 0.007564836],
       ['reg', 0.038427677],
       ['Low Fat', 0.099574908],
       ...,
       ['Low Fat', 0.073528561],
       ['Regular', 0.0],
       ['Regular', 0.104720151]], dtype=object)

In [9]:
C=ds[['Item_Type', 'Item_MRP']].values

In [10]:
C

array([['Snack Foods', 107.8622],
       ['Dairy', 87.3198],
       ['Others', 241.7538],
       ...,
       ['Health and Hygiene', 118.744],
       ['Canned', 214.6218],
       ['Canned', 79.796]], dtype=object)

In [11]:
D=ds[['Outlet_Identifier',
       'Outlet_Establishment_Year']].values

In [12]:
D

array([['OUT049', 1999],
       ['OUT017', 2007],
       ['OUT010', 1998],
       ...,
       ['OUT045', 2002],
       ['OUT017', 2007],
       ['OUT045', 2002]], dtype=object)

In [13]:
E=ds[['Outlet_Size']].values

In [14]:
E

array([['Medium'],
       [nan],
       [nan],
       ...,
       [nan],
       [nan],
       [nan]], dtype=object)

In [15]:
y=ds[['Outlet_Type']]

In [16]:
y

Outlet_Type
0     Supermarket Type1
1     Supermarket Type1
2         Grocery Store
3     Supermarket Type1
4     Supermarket Type3
...                 ...
5676  Supermarket Type1
5677  Supermarket Type2
5678  Supermarket Type1
5679  Supermarket Type1
5680  Supermarket Type1

[5681 rows x 1 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label_encode_A=LabelEncoder()

In [19]:
A[:,0]=label_encode_A.fit_transform(A[:,0])

In [20]:
A

array([[1103, 20.75],
       [1067, 8.3],
       [1406, 14.6],
       ...,
       [1412, 10.0],
       [517, 15.3],
       [987, 9.5]], dtype=object)

In [21]:
label_encode_B=LabelEncoder()

In [22]:
B[:,0]=label_encode_B.fit_transform(B[:,0])

In [23]:
B

array([[1, 0.007564836],
       [4, 0.038427677],
       [1, 0.099574908],
       ...,
       [1, 0.073528561],
       [2, 0.0],
       [2, 0.104720151]], dtype=object)

In [24]:
label_encode_C=LabelEncoder()

In [25]:
C[:,0]=label_encode_C.fit_transform(C[:,0])

In [26]:
C

array([[13, 107.8622],
       [4, 87.3198],
       [11, 241.7538],
       ...,
       [8, 118.744],
       [3, 214.6218],
       [3, 79.796]], dtype=object)

In [27]:
label_encode_D=LabelEncoder()

In [28]:
D[:,0]=label_encode_D.fit_transform(D[:,0])

In [29]:
D

array([[9, 1999],
       [2, 2007],
       [0, 1998],
       ...,
       [7, 2002],
       [2, 2007],
       [7, 2002]], dtype=object)

In [30]:
label_encode_E=LabelEncoder()

In [31]:
E[:,0]=label_encode_E.fit_transform(E[:,0])

In [32]:
E

array([[1],
       [3],
       [3],
       ...,
       [3],
       [3],
       [3]], dtype=object)

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe=OneHotEncoder()

In [35]:
ohe.fit_transform(ds.Item_Identifier.values.reshape(-1,1)).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
ohe.fit_transform(ds.Item_Fat_Content.values.reshape(-1,1)).toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
ohe.fit_transform(ds.Item_Type.values.reshape(-1,1)).toarray()

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
ohe.fit_transform(ds.Outlet_Identifier.values.reshape(-1,1)).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [39]:
ohe.fit_transform(ds.Outlet_Size.values.reshape(-1,1)).toarray()

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [40]:
label_encode_y=LabelEncoder()


In [41]:
y=label_encode_y.fit_transform(y)

c:\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [42]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
A_train,A_test,B_train,B_test,C_train,C_test,D_train,D_test,E_train,E_test,y_train,y_test=train_test_split(A,B,C,D,E,y,test_size=0.2,random_state=0)

In [45]:
A_train

array([[1304, 13.0],
       [539, 12.5],
       [878, nan],
       ...,
       [958, 20.25],
       [936, 19.85],
       [651, 7.72]], dtype=object)

In [46]:
A_test


array([[1469, 8.6],
       [1374, 12.15],
       [1303, nan],
       ...,
       [336, 9.195],
       [550, 9.8],
       [568, nan]], dtype=object)

In [47]:
B_train


array([[1, 0.035108732],
       [1, 0.0],
       [1, 0.140206849],
       ...,
       [2, 0.0],
       [2, 0.081387594],
       [2, 0.088364662]], dtype=object)

In [48]:
B_test

array([[1, 0.090331655],
       [0, 0.0],
       [1, 0.15579704],
       ...,
       [1, 0.108110205],
       [1, 0.026234055],
       [1, 0.049660306]], dtype=object)

In [49]:
C_train

array([[9, 49.6034],
       [3, 118.144],
       [1, 128.1994],
       ...,
       [3, 184.6924],
       [1, 166.0816],
       [6, 118.7466]], dtype=object)

In [50]:
C_test

array([[9, 115.8176],
       [11, 254.004],
       [9, 191.3504],
       ...,
       [13, 181.5634],
       [13, 214.385],
       [3, 163.4894]], dtype=object)

In [51]:
D_train

array([[8, 1997],
       [8, 1997],
       [5, 1985],
       ...,
       [6, 2004],
       [1, 1987],
       [8, 1997]], dtype=object)

In [52]:
D_test

array([[9, 1999],
       [9, 1999],
       [4, 1985],
       ...,
       [7, 2002],
       [2, 2007],
       [4, 1985]], dtype=object)

In [53]:
E_train

array([[2],
       [2],
       [1],
       ...,
       [2],
       [0],
       [2]], dtype=object)

In [54]:
E_test

array([[1],
       [1],
       [2],
       ...,
       [3],
       [3],
       [2]], dtype=object)

In [55]:
y_train

array([1, 1, 3, ..., 1, 1, 1])

In [56]:
y_test

array([1, 1, 0, ..., 1, 1, 0])

In [57]:
from sklearn.preprocessing import StandardScaler

In [58]:
SC_A=StandardScaler()

In [59]:
A_train=SC_A.fit_transform(A_train)

In [60]:
A_train

array([[ 1.1922513 ,  0.05382116],
       [-0.52802971, -0.05353586],
       [ 0.23429089,         nan],
       ...,
       [ 0.41418956,  1.61049791],
       [ 0.36471743,  1.5246123 ],
       [-0.27617157, -1.07986894]])